export const Home_Fetch_Exampledata_REQUEST=  "Home_Fetch_Exampledata_REQUEST"
export const Home_Fetch_Exampledata_SUCCESS = "Home_Fetch_Exampledata_SUCCESS"
export const Home_Fetch_Exampledata_FAILURE = "Home_Fetch_Exampledata_FAILURE"